/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuzanRouteImport } from './routes/suzan'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardTransactionsRouteImport } from './routes/dashboard.transactions'
import { Route as DashboardParametresRouteImport } from './routes/dashboard.parametres'
import { Route as DashboardMutuellesRouteImport } from './routes/dashboard.mutuelles'
import { Route as DashboardMesStatsRouteImport } from './routes/dashboard.mes-stats'
import { Route as DashboardFournisseursRouteImport } from './routes/dashboard.fournisseurs'
import { Route as DashboardDettesRouteImport } from './routes/dashboard.dettes'
import { Route as DashboardCommandesRouteImport } from './routes/dashboard.commandes'
import { Route as DashboardClientsRouteImport } from './routes/dashboard.clients'
import { Route as DashboardCaissesRouteImport } from './routes/dashboard.caisses'
import { Route as DashboardAgentVenteRouteImport } from './routes/dashboard.agent-vente'
import { Route as DashboardAgentMontageRouteImport } from './routes/dashboard.agent-montage'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardMutuellesIndexRouteImport } from './routes/dashboard.mutuelles.index'
import { Route as DashboardCommandesIndexRouteImport } from './routes/dashboard.commandes.index'
import { Route as DashboardClientsIndexRouteImport } from './routes/dashboard.clients.index'
import { Route as DashboardCaissesIndexRouteImport } from './routes/dashboard.caisses.index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as DashboardMutuellesNewRouteImport } from './routes/dashboard.mutuelles.new'
import { Route as DashboardMutuellesIdRouteImport } from './routes/dashboard.mutuelles.$id'
import { Route as DashboardCommandesNewRouteImport } from './routes/dashboard.commandes.new'
import { Route as DashboardCommandesIdRouteImport } from './routes/dashboard.commandes.$id'
import { Route as DashboardClientsIdRouteImport } from './routes/dashboard.clients.$id'
import { Route as DashboardCaissesIdRouteImport } from './routes/dashboard.caisses.$id'
import { Route as DashboardAdminPersonnelRouteImport } from './routes/dashboard.admin.personnel'
import { Route as ApiPublicHooksRunScheduledBackupRouteImport } from './routes/api/public/hooks/run-scheduled-backup'
import { Route as ApiPublicHooksAutoCloseCaissesRouteImport } from './routes/api/public/hooks/auto-close-caisses'

const SuzanRoute = SuzanRouteImport.update({
  id: '/suzan',
  path: '/suzan',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/dashboard/transactions',
  path: '/dashboard/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardParametresRoute = DashboardParametresRouteImport.update({
  id: '/dashboard/parametres',
  path: '/dashboard/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMutuellesRoute = DashboardMutuellesRouteImport.update({
  id: '/dashboard/mutuelles',
  path: '/dashboard/mutuelles',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMesStatsRoute = DashboardMesStatsRouteImport.update({
  id: '/dashboard/mes-stats',
  path: '/dashboard/mes-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFournisseursRoute = DashboardFournisseursRouteImport.update({
  id: '/dashboard/fournisseurs',
  path: '/dashboard/fournisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDettesRoute = DashboardDettesRouteImport.update({
  id: '/dashboard/dettes',
  path: '/dashboard/dettes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCommandesRoute = DashboardCommandesRouteImport.update({
  id: '/dashboard/commandes',
  path: '/dashboard/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/dashboard/clients',
  path: '/dashboard/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCaissesRoute = DashboardCaissesRouteImport.update({
  id: '/dashboard/caisses',
  path: '/dashboard/caisses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAgentVenteRoute = DashboardAgentVenteRouteImport.update({
  id: '/dashboard/agent-vente',
  path: '/dashboard/agent-vente',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAgentMontageRoute = DashboardAgentMontageRouteImport.update({
  id: '/dashboard/agent-montage',
  path: '/dashboard/agent-montage',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMutuellesIndexRoute = DashboardMutuellesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardMutuellesRoute,
} as any)
const DashboardCommandesIndexRoute = DashboardCommandesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCommandesRoute,
} as any)
const DashboardClientsIndexRoute = DashboardClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardClientsRoute,
} as any)
const DashboardCaissesIndexRoute = DashboardCaissesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCaissesRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardMutuellesNewRoute = DashboardMutuellesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardMutuellesRoute,
} as any)
const DashboardMutuellesIdRoute = DashboardMutuellesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardMutuellesRoute,
} as any)
const DashboardCommandesNewRoute = DashboardCommandesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardCommandesRoute,
} as any)
const DashboardCommandesIdRoute = DashboardCommandesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardCommandesRoute,
} as any)
const DashboardClientsIdRoute = DashboardClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardClientsRoute,
} as any)
const DashboardCaissesIdRoute = DashboardCaissesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardCaissesRoute,
} as any)
const DashboardAdminPersonnelRoute = DashboardAdminPersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const ApiPublicHooksRunScheduledBackupRoute =
  ApiPublicHooksRunScheduledBackupRouteImport.update({
    id: '/api/public/hooks/run-scheduled-backup',
    path: '/api/public/hooks/run-scheduled-backup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoCloseCaissesRoute =
  ApiPublicHooksAutoCloseCaissesRouteImport.update({
    id: '/api/public/hooks/auto-close-caisses',
    path: '/api/public/hooks/auto-close-caisses',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/suzan': typeof SuzanRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/agent-montage': typeof DashboardAgentMontageRoute
  '/dashboard/agent-vente': typeof DashboardAgentVenteRoute
  '/dashboard/caisses': typeof DashboardCaissesRouteWithChildren
  '/dashboard/clients': typeof DashboardClientsRouteWithChildren
  '/dashboard/commandes': typeof DashboardCommandesRouteWithChildren
  '/dashboard/dettes': typeof DashboardDettesRoute
  '/dashboard/fournisseurs': typeof DashboardFournisseursRoute
  '/dashboard/mes-stats': typeof DashboardMesStatsRoute
  '/dashboard/mutuelles': typeof DashboardMutuellesRouteWithChildren
  '/dashboard/parametres': typeof DashboardParametresRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/admin/personnel': typeof DashboardAdminPersonnelRoute
  '/dashboard/caisses/$id': typeof DashboardCaissesIdRoute
  '/dashboard/clients/$id': typeof DashboardClientsIdRoute
  '/dashboard/commandes/$id': typeof DashboardCommandesIdRoute
  '/dashboard/commandes/new': typeof DashboardCommandesNewRoute
  '/dashboard/mutuelles/$id': typeof DashboardMutuellesIdRoute
  '/dashboard/mutuelles/new': typeof DashboardMutuellesNewRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/caisses/': typeof DashboardCaissesIndexRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
  '/dashboard/commandes/': typeof DashboardCommandesIndexRoute
  '/dashboard/mutuelles/': typeof DashboardMutuellesIndexRoute
  '/api/public/hooks/auto-close-caisses': typeof ApiPublicHooksAutoCloseCaissesRoute
  '/api/public/hooks/run-scheduled-backup': typeof ApiPublicHooksRunScheduledBackupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/suzan': typeof SuzanRoute
  '/dashboard/agent-montage': typeof DashboardAgentMontageRoute
  '/dashboard/agent-vente': typeof DashboardAgentVenteRoute
  '/dashboard/dettes': typeof DashboardDettesRoute
  '/dashboard/fournisseurs': typeof DashboardFournisseursRoute
  '/dashboard/mes-stats': typeof DashboardMesStatsRoute
  '/dashboard/parametres': typeof DashboardParametresRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/admin/personnel': typeof DashboardAdminPersonnelRoute
  '/dashboard/caisses/$id': typeof DashboardCaissesIdRoute
  '/dashboard/clients/$id': typeof DashboardClientsIdRoute
  '/dashboard/commandes/$id': typeof DashboardCommandesIdRoute
  '/dashboard/commandes/new': typeof DashboardCommandesNewRoute
  '/dashboard/mutuelles/$id': typeof DashboardMutuellesIdRoute
  '/dashboard/mutuelles/new': typeof DashboardMutuellesNewRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/caisses': typeof DashboardCaissesIndexRoute
  '/dashboard/clients': typeof DashboardClientsIndexRoute
  '/dashboard/commandes': typeof DashboardCommandesIndexRoute
  '/dashboard/mutuelles': typeof DashboardMutuellesIndexRoute
  '/api/public/hooks/auto-close-caisses': typeof ApiPublicHooksAutoCloseCaissesRoute
  '/api/public/hooks/run-scheduled-backup': typeof ApiPublicHooksRunScheduledBackupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/suzan': typeof SuzanRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/agent-montage': typeof DashboardAgentMontageRoute
  '/dashboard/agent-vente': typeof DashboardAgentVenteRoute
  '/dashboard/caisses': typeof DashboardCaissesRouteWithChildren
  '/dashboard/clients': typeof DashboardClientsRouteWithChildren
  '/dashboard/commandes': typeof DashboardCommandesRouteWithChildren
  '/dashboard/dettes': typeof DashboardDettesRoute
  '/dashboard/fournisseurs': typeof DashboardFournisseursRoute
  '/dashboard/mes-stats': typeof DashboardMesStatsRoute
  '/dashboard/mutuelles': typeof DashboardMutuellesRouteWithChildren
  '/dashboard/parametres': typeof DashboardParametresRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/admin/personnel': typeof DashboardAdminPersonnelRoute
  '/dashboard/caisses/$id': typeof DashboardCaissesIdRoute
  '/dashboard/clients/$id': typeof DashboardClientsIdRoute
  '/dashboard/commandes/$id': typeof DashboardCommandesIdRoute
  '/dashboard/commandes/new': typeof DashboardCommandesNewRoute
  '/dashboard/mutuelles/$id': typeof DashboardMutuellesIdRoute
  '/dashboard/mutuelles/new': typeof DashboardMutuellesNewRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/caisses/': typeof DashboardCaissesIndexRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
  '/dashboard/commandes/': typeof DashboardCommandesIndexRoute
  '/dashboard/mutuelles/': typeof DashboardMutuellesIndexRoute
  '/api/public/hooks/auto-close-caisses': typeof ApiPublicHooksAutoCloseCaissesRoute
  '/api/public/hooks/run-scheduled-backup': typeof ApiPublicHooksRunScheduledBackupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/suzan'
    | '/dashboard/admin'
    | '/dashboard/agent-montage'
    | '/dashboard/agent-vente'
    | '/dashboard/caisses'
    | '/dashboard/clients'
    | '/dashboard/commandes'
    | '/dashboard/dettes'
    | '/dashboard/fournisseurs'
    | '/dashboard/mes-stats'
    | '/dashboard/mutuelles'
    | '/dashboard/parametres'
    | '/dashboard/transactions'
    | '/dashboard/admin/personnel'
    | '/dashboard/caisses/$id'
    | '/dashboard/clients/$id'
    | '/dashboard/commandes/$id'
    | '/dashboard/commandes/new'
    | '/dashboard/mutuelles/$id'
    | '/dashboard/mutuelles/new'
    | '/dashboard/admin/'
    | '/dashboard/caisses/'
    | '/dashboard/clients/'
    | '/dashboard/commandes/'
    | '/dashboard/mutuelles/'
    | '/api/public/hooks/auto-close-caisses'
    | '/api/public/hooks/run-scheduled-backup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/suzan'
    | '/dashboard/agent-montage'
    | '/dashboard/agent-vente'
    | '/dashboard/dettes'
    | '/dashboard/fournisseurs'
    | '/dashboard/mes-stats'
    | '/dashboard/parametres'
    | '/dashboard/transactions'
    | '/dashboard/admin/personnel'
    | '/dashboard/caisses/$id'
    | '/dashboard/clients/$id'
    | '/dashboard/commandes/$id'
    | '/dashboard/commandes/new'
    | '/dashboard/mutuelles/$id'
    | '/dashboard/mutuelles/new'
    | '/dashboard/admin'
    | '/dashboard/caisses'
    | '/dashboard/clients'
    | '/dashboard/commandes'
    | '/dashboard/mutuelles'
    | '/api/public/hooks/auto-close-caisses'
    | '/api/public/hooks/run-scheduled-backup'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/suzan'
    | '/dashboard/admin'
    | '/dashboard/agent-montage'
    | '/dashboard/agent-vente'
    | '/dashboard/caisses'
    | '/dashboard/clients'
    | '/dashboard/commandes'
    | '/dashboard/dettes'
    | '/dashboard/fournisseurs'
    | '/dashboard/mes-stats'
    | '/dashboard/mutuelles'
    | '/dashboard/parametres'
    | '/dashboard/transactions'
    | '/dashboard/admin/personnel'
    | '/dashboard/caisses/$id'
    | '/dashboard/clients/$id'
    | '/dashboard/commandes/$id'
    | '/dashboard/commandes/new'
    | '/dashboard/mutuelles/$id'
    | '/dashboard/mutuelles/new'
    | '/dashboard/admin/'
    | '/dashboard/caisses/'
    | '/dashboard/clients/'
    | '/dashboard/commandes/'
    | '/dashboard/mutuelles/'
    | '/api/public/hooks/auto-close-caisses'
    | '/api/public/hooks/run-scheduled-backup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SuzanRoute: typeof SuzanRoute
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardAgentMontageRoute: typeof DashboardAgentMontageRoute
  DashboardAgentVenteRoute: typeof DashboardAgentVenteRoute
  DashboardCaissesRoute: typeof DashboardCaissesRouteWithChildren
  DashboardClientsRoute: typeof DashboardClientsRouteWithChildren
  DashboardCommandesRoute: typeof DashboardCommandesRouteWithChildren
  DashboardDettesRoute: typeof DashboardDettesRoute
  DashboardFournisseursRoute: typeof DashboardFournisseursRoute
  DashboardMesStatsRoute: typeof DashboardMesStatsRoute
  DashboardMutuellesRoute: typeof DashboardMutuellesRouteWithChildren
  DashboardParametresRoute: typeof DashboardParametresRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  ApiPublicHooksAutoCloseCaissesRoute: typeof ApiPublicHooksAutoCloseCaissesRoute
  ApiPublicHooksRunScheduledBackupRoute: typeof ApiPublicHooksRunScheduledBackupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suzan': {
      id: '/suzan'
      path: '/suzan'
      fullPath: '/suzan'
      preLoaderRoute: typeof SuzanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/transactions': {
      id: '/dashboard/transactions'
      path: '/dashboard/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/parametres': {
      id: '/dashboard/parametres'
      path: '/dashboard/parametres'
      fullPath: '/dashboard/parametres'
      preLoaderRoute: typeof DashboardParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/mutuelles': {
      id: '/dashboard/mutuelles'
      path: '/dashboard/mutuelles'
      fullPath: '/dashboard/mutuelles'
      preLoaderRoute: typeof DashboardMutuellesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/mes-stats': {
      id: '/dashboard/mes-stats'
      path: '/dashboard/mes-stats'
      fullPath: '/dashboard/mes-stats'
      preLoaderRoute: typeof DashboardMesStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/fournisseurs': {
      id: '/dashboard/fournisseurs'
      path: '/dashboard/fournisseurs'
      fullPath: '/dashboard/fournisseurs'
      preLoaderRoute: typeof DashboardFournisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/dettes': {
      id: '/dashboard/dettes'
      path: '/dashboard/dettes'
      fullPath: '/dashboard/dettes'
      preLoaderRoute: typeof DashboardDettesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/commandes': {
      id: '/dashboard/commandes'
      path: '/dashboard/commandes'
      fullPath: '/dashboard/commandes'
      preLoaderRoute: typeof DashboardCommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/clients': {
      id: '/dashboard/clients'
      path: '/dashboard/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/caisses': {
      id: '/dashboard/caisses'
      path: '/dashboard/caisses'
      fullPath: '/dashboard/caisses'
      preLoaderRoute: typeof DashboardCaissesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/agent-vente': {
      id: '/dashboard/agent-vente'
      path: '/dashboard/agent-vente'
      fullPath: '/dashboard/agent-vente'
      preLoaderRoute: typeof DashboardAgentVenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/agent-montage': {
      id: '/dashboard/agent-montage'
      path: '/dashboard/agent-montage'
      fullPath: '/dashboard/agent-montage'
      preLoaderRoute: typeof DashboardAgentMontageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/mutuelles/': {
      id: '/dashboard/mutuelles/'
      path: '/'
      fullPath: '/dashboard/mutuelles/'
      preLoaderRoute: typeof DashboardMutuellesIndexRouteImport
      parentRoute: typeof DashboardMutuellesRoute
    }
    '/dashboard/commandes/': {
      id: '/dashboard/commandes/'
      path: '/'
      fullPath: '/dashboard/commandes/'
      preLoaderRoute: typeof DashboardCommandesIndexRouteImport
      parentRoute: typeof DashboardCommandesRoute
    }
    '/dashboard/clients/': {
      id: '/dashboard/clients/'
      path: '/'
      fullPath: '/dashboard/clients/'
      preLoaderRoute: typeof DashboardClientsIndexRouteImport
      parentRoute: typeof DashboardClientsRoute
    }
    '/dashboard/caisses/': {
      id: '/dashboard/caisses/'
      path: '/'
      fullPath: '/dashboard/caisses/'
      preLoaderRoute: typeof DashboardCaissesIndexRouteImport
      parentRoute: typeof DashboardCaissesRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/mutuelles/new': {
      id: '/dashboard/mutuelles/new'
      path: '/new'
      fullPath: '/dashboard/mutuelles/new'
      preLoaderRoute: typeof DashboardMutuellesNewRouteImport
      parentRoute: typeof DashboardMutuellesRoute
    }
    '/dashboard/mutuelles/$id': {
      id: '/dashboard/mutuelles/$id'
      path: '/$id'
      fullPath: '/dashboard/mutuelles/$id'
      preLoaderRoute: typeof DashboardMutuellesIdRouteImport
      parentRoute: typeof DashboardMutuellesRoute
    }
    '/dashboard/commandes/new': {
      id: '/dashboard/commandes/new'
      path: '/new'
      fullPath: '/dashboard/commandes/new'
      preLoaderRoute: typeof DashboardCommandesNewRouteImport
      parentRoute: typeof DashboardCommandesRoute
    }
    '/dashboard/commandes/$id': {
      id: '/dashboard/commandes/$id'
      path: '/$id'
      fullPath: '/dashboard/commandes/$id'
      preLoaderRoute: typeof DashboardCommandesIdRouteImport
      parentRoute: typeof DashboardCommandesRoute
    }
    '/dashboard/clients/$id': {
      id: '/dashboard/clients/$id'
      path: '/$id'
      fullPath: '/dashboard/clients/$id'
      preLoaderRoute: typeof DashboardClientsIdRouteImport
      parentRoute: typeof DashboardClientsRoute
    }
    '/dashboard/caisses/$id': {
      id: '/dashboard/caisses/$id'
      path: '/$id'
      fullPath: '/dashboard/caisses/$id'
      preLoaderRoute: typeof DashboardCaissesIdRouteImport
      parentRoute: typeof DashboardCaissesRoute
    }
    '/dashboard/admin/personnel': {
      id: '/dashboard/admin/personnel'
      path: '/personnel'
      fullPath: '/dashboard/admin/personnel'
      preLoaderRoute: typeof DashboardAdminPersonnelRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/api/public/hooks/run-scheduled-backup': {
      id: '/api/public/hooks/run-scheduled-backup'
      path: '/api/public/hooks/run-scheduled-backup'
      fullPath: '/api/public/hooks/run-scheduled-backup'
      preLoaderRoute: typeof ApiPublicHooksRunScheduledBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-close-caisses': {
      id: '/api/public/hooks/auto-close-caisses'
      path: '/api/public/hooks/auto-close-caisses'
      fullPath: '/api/public/hooks/auto-close-caisses'
      preLoaderRoute: typeof ApiPublicHooksAutoCloseCaissesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminPersonnelRoute: typeof DashboardAdminPersonnelRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminPersonnelRoute: DashboardAdminPersonnelRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardCaissesRouteChildren {
  DashboardCaissesIdRoute: typeof DashboardCaissesIdRoute
  DashboardCaissesIndexRoute: typeof DashboardCaissesIndexRoute
}

const DashboardCaissesRouteChildren: DashboardCaissesRouteChildren = {
  DashboardCaissesIdRoute: DashboardCaissesIdRoute,
  DashboardCaissesIndexRoute: DashboardCaissesIndexRoute,
}

const DashboardCaissesRouteWithChildren =
  DashboardCaissesRoute._addFileChildren(DashboardCaissesRouteChildren)

interface DashboardClientsRouteChildren {
  DashboardClientsIdRoute: typeof DashboardClientsIdRoute
  DashboardClientsIndexRoute: typeof DashboardClientsIndexRoute
}

const DashboardClientsRouteChildren: DashboardClientsRouteChildren = {
  DashboardClientsIdRoute: DashboardClientsIdRoute,
  DashboardClientsIndexRoute: DashboardClientsIndexRoute,
}

const DashboardClientsRouteWithChildren =
  DashboardClientsRoute._addFileChildren(DashboardClientsRouteChildren)

interface DashboardCommandesRouteChildren {
  DashboardCommandesIdRoute: typeof DashboardCommandesIdRoute
  DashboardCommandesNewRoute: typeof DashboardCommandesNewRoute
  DashboardCommandesIndexRoute: typeof DashboardCommandesIndexRoute
}

const DashboardCommandesRouteChildren: DashboardCommandesRouteChildren = {
  DashboardCommandesIdRoute: DashboardCommandesIdRoute,
  DashboardCommandesNewRoute: DashboardCommandesNewRoute,
  DashboardCommandesIndexRoute: DashboardCommandesIndexRoute,
}

const DashboardCommandesRouteWithChildren =
  DashboardCommandesRoute._addFileChildren(DashboardCommandesRouteChildren)

interface DashboardMutuellesRouteChildren {
  DashboardMutuellesIdRoute: typeof DashboardMutuellesIdRoute
  DashboardMutuellesNewRoute: typeof DashboardMutuellesNewRoute
  DashboardMutuellesIndexRoute: typeof DashboardMutuellesIndexRoute
}

const DashboardMutuellesRouteChildren: DashboardMutuellesRouteChildren = {
  DashboardMutuellesIdRoute: DashboardMutuellesIdRoute,
  DashboardMutuellesNewRoute: DashboardMutuellesNewRoute,
  DashboardMutuellesIndexRoute: DashboardMutuellesIndexRoute,
}

const DashboardMutuellesRouteWithChildren =
  DashboardMutuellesRoute._addFileChildren(DashboardMutuellesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SuzanRoute: SuzanRoute,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardAgentMontageRoute: DashboardAgentMontageRoute,
  DashboardAgentVenteRoute: DashboardAgentVenteRoute,
  DashboardCaissesRoute: DashboardCaissesRouteWithChildren,
  DashboardClientsRoute: DashboardClientsRouteWithChildren,
  DashboardCommandesRoute: DashboardCommandesRouteWithChildren,
  DashboardDettesRoute: DashboardDettesRoute,
  DashboardFournisseursRoute: DashboardFournisseursRoute,
  DashboardMesStatsRoute: DashboardMesStatsRoute,
  DashboardMutuellesRoute: DashboardMutuellesRouteWithChildren,
  DashboardParametresRoute: DashboardParametresRoute,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  ApiPublicHooksAutoCloseCaissesRoute: ApiPublicHooksAutoCloseCaissesRoute,
  ApiPublicHooksRunScheduledBackupRoute: ApiPublicHooksRunScheduledBackupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
